name = "my-todos"
compatibility_date = "2024-01-16"

[build]
command = "npm run build"
node_compat = true

[build.environment]
NODE_VERSION = "18.18.0"

[site]
bucket = ".vercel/output/static"

[node]
version = "18.18.0"  